<?php

/**
 * Implements hook_block_info().
 * Информация о блоке и дефолтные настройки.
 */
function fts_lights_field_formatter_info() {
  return array(
    'facebooklink_formatter' => array( //Machine name of the formatter
      'label' => t('FTS lights'),
      'field types' => array('image'), //This will only be available to text fields
      'settings'  => array( //Array of the settings we'll create
        'slide_size' => 'Large', //give a default value for when the form is first loaded
        'link_size' => 'Large',
        'slides' => 'NO',
      //   'tooltip' => 'Link to user Facebook page', //ditto
      ),
    ),
  );
}





/**
 * Implements hook_field_formatter_settings_form().
 */




function fts_lights_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  //This gets the view_mode where our settings are stored
  $display = $instance['display'][$view_mode];
  //This gets the actual settings
  $settings = $display['settings'];
  //Initialize the element variable
  $element = array();
  //Add your select box

$image_style = db_select('image_styles', 's');
$image_style->fields('s', array('name'));
$image_style = $image_style->execute()->fetchAll();
$image_styles = array();
  foreach ($image_style as $delta => $item) {
    $image_styles[$item->name] = $item->name;
  }

  $element['slide_size'] = array(
    '#type'           => 'select',                           // Use a select box widget
    '#title'          => t('Select the slide style'),                   // Widget label
    '#default_value'  => $settings['slide_size'],              // Get the value if it's already been set
    '#options'        => $image_styles,
  );
  $element['link_size'] = array(
    '#type'           => 'select',                           // Use a select box widget
    '#title'          => t('Select the slide link'),                   // Widget label
    '#default_value'  => $settings['link_size'],              // Get the value if it's already been set
    '#options'        => $image_styles,
  );
  $element['slides'] = array(
    '#type'           => 'select',                           // Use a select box widget
    '#title'          => t('Slides'),                   // Widget label
    '#default_value'  => $settings['slides'],              // Get the value if it's already been set
    '#options'        => array('NO' => 'NO', 'horizontal' => 'horizontal'),
  );
  return $element;
}






/**
 * Implements hook_field_formatter_settings_summary().
 */
function fts_lights_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = t('Side: @size<br />Link: @link<br />Slides: @slides', array(
    '@size'  => $settings['slide_size'],
    '@link'  => $settings['link_size'],
    '@slides'  => $settings['slides'],
  )); // we use t() for translation and placeholders to guard against attacks
  return $summary;
}





/**
 * Implements hook_field_formatter_view().
 */
function fts_lights_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array(); // Initialize the var
  $settings = $display['settings']; // get the settings
  $size = $settings['slide_size']; // The Size setting selected in the settings form
  $link = $settings['link_size'];
  $slides = $settings['slides'];
  // Create the image - Note that I'm storing the images in our module but they could be anywhere
  // $image = '<img src="/' . drupal_get_path('module', 'fts_lights') . 'gallery-' . 'size' . '.png">';
  $fb1 = '';
  foreach ($items as $delta => $item) {
  	$fb1 = $fb1.'<a href="'.image_style_url($link, $item['uri']).'" data-thumb="'.image_style_url($size, $item['uri']).'" class="fts_lights_item"><img src="'.image_style_url($size, $item['uri']).'""></a>';
    // $fb2 = $fb2.'<div><img src="'.image_style_url($size, $item['uri']).'""></div>';
  }
  $options = array(
    'html'        => TRUE, // This tells Drupal that we're sending HTML, not plain text, otherwise it would encode it
    // 'attributes'  => array(
    //   'title' => $tooltip, // This sets our tooltip
    //   ),
    );
if ($slides == 'horizontal') {
	$element[0]['#markup'] = '<div class="fts_lights fts_lights_gallery fts_lights_slider">'.$fb1.'</div>';
} else {
  $element[0]['#markup'] = '<div class="fts_lights fts_lights_gallery">'.$fb1.'</div>';
}

drupal_add_js('sites/all/libraries/lightslider/dist/js/lightslider.min.js');
drupal_add_css('sites/all/libraries/lightslider/dist/css/lightslider.min.css');
drupal_add_js('sites/all/libraries/lightgallery/dist/js/lightgallery-all.min.js');
drupal_add_css('sites/all/libraries/lightgallery/dist/css/lightgallery.min.css');






  return $element;
}





// libraries
